name: CloudFormation Linter

on: [pull_request]

jobs:
  cfn-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: vpc-cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: vpc/*.yml
